services:
  keycloak_postgres:
    container_name: keycloak_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    expose:
      - "5432"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8443:8443"
      - "8444:8080"
    volumes:
      - "./ssl/keycloak/:/opt/keycloak/conf/"
      - ./keycloak/themes/dev:/opt/keycloak/themes/dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_URL}
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB: postgres
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8080
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key.pem
    depends_on:
      - keycloak_postgres
    networks:
      - keycloak-network
    command:
      - "start"

networks:
  keycloak-network:
    name: keycloak-network
    driver: bridge
